import type { InspectionResult } from './mock-data';

const DAY_MS = 24 * 60 * 60 * 1000;

function daysAgoToIso(daysAgo: number, hourUtc: number, minuteUtc: number): string {
  const date = new Date(Date.now() - daysAgo * DAY_MS);
  date.setUTCHours(hourUtc, minuteUtc, 0, 0);
  return date.toISOString();
}

export const DEMO_SEED_INSPECTIONS: InspectionResult[] = [
  {
    id: 'seed-insp-001',
    filename: 'WT-001_B1_LE_PASS_01.jpg',
    timestamp: daysAgoToIso(2, 14, 12),
    turbineId: 'WT-001',
    bladeNumber: 1,
    detections: [
      {
        id: 'seed-det-001a',
        class: 'LE erosion',
        confidence: 0.91,
        severity: 'critical',
        bbox: { x: 27.4, y: 11.8, w: 14.6, h: 20.2 },
        description: 'Heavy pitting on the leading edge with coating loss over roughly 0.5 m span.',
      },
      {
        id: 'seed-det-001b',
        class: 'VG;MT',
        confidence: 0.82,
        severity: 'minor',
        bbox: { x: 63.1, y: 37.2, w: 5.4, h: 4.8 },
        description: 'One vortex generator appears detached from adhesive bed; verify during rope access.',
      },
    ],
    inferenceTime: 284,
    imageWidth: 5472,
    imageHeight: 3648,
    tilesProcessed: 64,
  },
  {
    id: 'seed-insp-002',
    filename: 'WT-002_B3_TE_ROUTE_07.jpg',
    timestamp: daysAgoToIso(5, 9, 34),
    turbineId: 'WT-002',
    bladeNumber: 3,
    detections: [
      {
        id: 'seed-det-002a',
        class: 'surface crack',
        confidence: 0.76,
        severity: 'major',
        bbox: { x: 42.7, y: 48.3, w: 7.1, h: 12.5 },
        description: 'Longitudinal crack near mid-span pressure side; length estimated at 18-22 cm.',
      },
      {
        id: 'seed-det-002b',
        class: 'trailing edge split',
        confidence: 0.88,
        severity: 'critical',
        bbox: { x: 71.2, y: 22.5, w: 9.8, h: 24.1 },
        description: 'Visible trailing-edge opening with probable bond-line separation and moisture ingress risk.',
      },
    ],
    inferenceTime: 512,
    imageWidth: 6000,
    imageHeight: 4000,
    tilesProcessed: 72,
  },
  {
    id: 'seed-insp-003',
    filename: 'WT-003_B2_LIGHTNING_03.jpg',
    timestamp: daysAgoToIso(8, 16, 3),
    turbineId: 'WT-003',
    bladeNumber: 2,
    detections: [
      {
        id: 'seed-det-003a',
        class: 'lightning damage',
        confidence: 0.93,
        severity: 'critical',
        bbox: { x: 45.8, y: 18.9, w: 16.4, h: 29.6 },
        description: 'Burned laminate and receptor impact point suggest recent strike; immediate shutdown advised.',
      },
    ],
    inferenceTime: 744,
    imageWidth: 6240,
    imageHeight: 4160,
    tilesProcessed: 81,
  },
  {
    id: 'seed-insp-004',
    filename: 'WT-004_B1_ROOT_SECTION_02.jpg',
    timestamp: daysAgoToIso(12, 11, 48),
    turbineId: 'WT-004',
    bladeNumber: 1,
    detections: [
      {
        id: 'seed-det-004a',
        class: 'surface crack',
        confidence: 0.71,
        severity: 'major',
        bbox: { x: 33.4, y: 58.8, w: 6.2, h: 10.9 },
        description: 'Cross-fiber surface crack near root transition; monitor for propagation in next cycle.',
      },
      {
        id: 'seed-det-004b',
        class: 'VG;MT',
        confidence: 0.65,
        severity: 'minor',
        bbox: { x: 58.7, y: 40.6, w: 4.6, h: 3.9 },
        description: 'VG tab partially lifted with debris accumulation; schedule re-bond and clean.',
      },
    ],
    inferenceTime: 236,
    imageWidth: 5184,
    imageHeight: 3456,
    tilesProcessed: 49,
  },
  {
    id: 'seed-insp-005',
    filename: 'WT-005_B2_SPAN_SWEEP_05.jpg',
    timestamp: daysAgoToIso(16, 13, 27),
    turbineId: 'WT-005',
    bladeNumber: 2,
    detections: [
      {
        id: 'seed-det-005a',
        class: 'LE erosion',
        confidence: 0.89,
        severity: 'critical',
        bbox: { x: 18.6, y: 9.7, w: 13.2, h: 26.5 },
        description: 'Leading edge shell erosion with exposed filler material over extended outer-span section.',
      },
      {
        id: 'seed-det-005b',
        class: 'trailing edge split',
        confidence: 0.79,
        severity: 'major',
        bbox: { x: 66.9, y: 30.8, w: 8.6, h: 17.4 },
        description: 'Narrow split along trailing edge likely linked to fatigue loading at bonded seam.',
      },
      {
        id: 'seed-det-005c',
        class: 'surface crack',
        confidence: 0.67,
        severity: 'major',
        bbox: { x: 50.2, y: 53.1, w: 5.7, h: 9.4 },
        description: 'Secondary crack cluster around repaired patch; recommend detailed close-up survey.',
      },
    ],
    inferenceTime: 603,
    imageWidth: 5472,
    imageHeight: 3648,
    tilesProcessed: 70,
  },
  {
    id: 'seed-insp-006',
    filename: 'WT-001_B3_RECEIVER_ZONE_04.jpg',
    timestamp: daysAgoToIso(21, 8, 56),
    turbineId: 'WT-001',
    bladeNumber: 3,
    detections: [
      {
        id: 'seed-det-006a',
        class: 'lightning damage',
        confidence: 0.84,
        severity: 'critical',
        bbox: { x: 40.1, y: 14.5, w: 12.7, h: 22.9 },
        description: 'Localized flashover marks around receptor strip and paint blistering.',
      },
      {
        id: 'seed-det-006b',
        class: 'VG;MT',
        confidence: 0.62,
        severity: 'minor',
        bbox: { x: 72.6, y: 46.4, w: 4.2, h: 4.7 },
        description: 'Possible missing vortex generator on suction side; low confidence due motion blur.',
      },
    ],
    inferenceTime: 430,
    imageWidth: 5760,
    imageHeight: 3840,
    tilesProcessed: 58,
  },
  {
    id: 'seed-insp-007',
    filename: 'WT-002_B1_TIP_SECTION_09.jpg',
    timestamp: daysAgoToIso(27, 15, 11),
    turbineId: 'WT-002',
    bladeNumber: 1,
    detections: [
      {
        id: 'seed-det-007a',
        class: 'LE erosion',
        confidence: 0.74,
        severity: 'major',
        bbox: { x: 22.8, y: 7.4, w: 11.5, h: 15.1 },
        description: 'Early-stage leading edge roughness and rain erosion in tip region.',
      },
      {
        id: 'seed-det-007b',
        class: 'trailing edge split',
        confidence: 0.69,
        severity: 'major',
        bbox: { x: 76.2, y: 19.7, w: 7.3, h: 13.6 },
        description: 'Hairline split observed near the trailing edge cap; recommend interval tracking.',
      },
    ],
    inferenceTime: 372,
    imageWidth: 5472,
    imageHeight: 3648,
    tilesProcessed: 55,
  },
];
